// HOME
export const LOAD_HOME_PHOTOS = "LOAD_HOME_PHOTOS";
export const SHOW_HOME_LOADING = "SHOW_HOME_LOADING";
export const SHOW_HOME_ERROR = "SHOW_HOME_ERROR";
export const CLEAR_HOME_PHOTOS = "CLEAR_HOME_PHOTOS";

//Search
export const LOAD_SEARCH_PHOTOS = "LOAD_SEARCH_PHOTOS";
export const SHOW_SEARCH_LOADING = "SHOW_SEARCH_LOADING";
export const SHOW_SEARCH_ERROR = "SHOW_SEARCH_ERROR";
export const CLEAR_SEARCH_PHOTOS = "CLEAR_SEARCH_PHOTOS";

// Detail
export const LOAD_PHOTO_DETAIL = "LOAD_PHOTO_DETAIL";
export const CLEAR_PHOTO_DETAIL = "CLEAR_PHOTO_DETAIL";

// Detail
export const LOAD_RANDOM_PHOTO = "LOAD_RANDOM_PHOTO";
export const CLEAR_RANDOM_PHOTO = "CLEAR_RANDOM_PHOTO";

// UI
export const INCREMENT_PAGE = "INCREMENT_PAGE";
export const FETCH_REQUEST = "FETCH_REQUEST";
export const FINISH_REQUEST = "FINISH_REQUEST";
export const GET_PHOTOS_LIST = "GET_PHOTOS_LIST";
export const RESET_PAGE = "RESET_PAGE";

// Auth
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
