// HOME
export const LOAD_HOME_PHOTOS = "LOAD_HOME_PHOTOS";
export const SHOW_HOME_LOADING = "SHOW_HOME_LOADING";
export const SHOW_HOME_ERROR = "SHOW_HOME_ERROR";

//Search
export const LOAD_SEARCH_PHOTOS = "LOAD_SEARCH_PHOTOS";
export const SHOW_SEARCH_LOADING = "SHOW_SEARCH_LOADING";
export const SHOW_SEARCH_ERROR = "SHOW_SEARCH_ERROR";
export const CLEAR_SEARCH_PHOTOS = "CLEAR_SEARCH_PHOTOS";

// Detail
export const LOAD_PHOTO_DETAIL = "LOAD_PHOTO_DETAIL";

// Detail
export const LOAD_RANDOM_PHOTO = "LOAD_RANDOM_PHOTO";
